projects:
  apis:
    schemaPath: amplify/backend/api/apis/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - awsAPIs.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: awsAPIs.ts
        docsFilePath: src/graphql
        region: eu-west-2
        apiId: null
        maxDepth: 2
